Component protocol default protocol yml support i18n
erda-project/erda-infra pull request #215
Opened 2022-01-19 12:20 UTC by shuofan

#### What this PR does / why we need it:
Component protocol default protocol yml support i18n

#### Which issue(s) this PR fixes:
Fixes #

#### Specified Reivewers:
/assign @sfwn

2022-01-20 02:12 UTC, sfwn requested changes

2022-01-20 02:12 UTC, sfwn commented on providers/component-protocol/protocol.service.go
> +	if err := protocol.RunScenarioRender(ctx, renderReq, sdk.Tran); err != nil {
get tran from ctx.sdk

2022-01-20 02:12 UTC, sfwn commented on providers/component-protocol/protocol/protocol.go
> +			return cptype.ComponentProtocol{}, fmt.Errorf(i18n(ctx, "${default.protocol.not.exist}, ${scenario}: %s", scenario))
dup with L104

2022-01-20 02:12 UTC, sfwn commented on providers/component-protocol/protocol/protocol.go
> +		if len(v) == 2 && strings.HasPrefix(v[1], I18n+".") {
use strutil.ReplaceAllStringSubmatchFunc()

2022-01-20 10:14 UTC, sfwn requested changes

2022-01-20 10:14 UTC, sfwn commented on providers/component-protocol/protocol/protocol.go
> +		defaultProtocolsRaw[p.Scenario] = string(protocolYAML)
add only when yaml match cp placeholder regex for performance consider.

2022-01-20 11:21 UTC, sfwn requested changes

2022-01-20 11:21 UTC, sfwn commented on providers/component-protocol/protocol/protocol.go
> +		s, ok := defaultProtocols[scenario]
use `p` uniformly as before

2022-01-20 11:26 UTC, shuofan commented on providers/component-protocol/protocol/protocol.go
> +		s, ok := defaultProtocols[scenario]
done

2022-01-20 11:39 UTC, sfwn approved these changes

2022-01-20 11:40 UTC, sfwn commented
/approve

2022-01-20 11:41 UTC, merged

2022-01-21 03:24 UTC, sfwn commented
/cherry-pick release/1.6-alpha2

2022-01-25 07:46 UTC, shuofan commented
/cherry-pick release/1.5-for-i18n