cp: fix render posthook for parallel
erda-project/erda-infra pull request #220
Opened 2022-01-24 06:34 UTC by sfwn

#### What this PR does / why we need it:

add missing posthook for parallel rendering

#### Specified Reivewers:

/assign @Effet

2022-01-25 02:44 UTC, Effet requested changes

2022-01-25 02:44 UTC, Effet commented on providers/component-protocol/protocol/render.go
> +		goto POSTHOOK
should not use `goto`

2022-01-26 08:01 UTC, Effet submitted a review, later dismissed

2022-01-26 08:03 UTC, sfwn commented on providers/component-protocol/protocol/render.go
> +		goto POSTHOOK
adjusted

2022-01-26 08:07 UTC, Effet approved these changes

2022-01-26 08:07 UTC, merged